SELECT * FROM DATABASE.TABLE MAX(COLUMN) ORDER BY DESC LIMIT 2;





FIRST QUERY TO PRINT THEH CONTENTS OF THE TABLE WITH A LIMIT OF TWO ROWS. 


		SECOND QUERY WILL PRINT THE DESCENDING ORDER OF THE OUTPUT OF FIRST QUERY AND WE WILL LIMIT ONLY 1;
